### ISSUE TITLE
Large margin on settings tool box

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#1013]
**Describe the bug**
After the settings sidebar changes and scrolling to the top of the page, a large margin appears.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [link removed] (XFP 6.0.2)
2. Click on **Business Phone**
3. Scroll to the top of the page

**Expected behaviour**
There should be no margin suddenly popping out.

**Screenshots**

**Affected browsers**
 - OS: MacOS
 - Browser: Chrome
 - Version: `76.0.3809.100 (Official Build) (64-bit)`

---

 - OS: MacOS
 - Browser: Chrome
 - Version: `75.0.3770.80 (Official Build) (64-bit)`

---

 - OS: MacOS
 - Browser: Firefox
 - Version: `64.0.2`

**Comment by Stanton** [comment]
Believe this to be an incorrect value being stored as the outerHeight in the `sticky_settings_form.js` file in the XFP repository. There may be a way in Pulsar to resolve this by giving the settings sidebar a max-width...
