### ISSUE TITLE
Long messages or errors need wrapping 

### ISSUE THREAD

**Issue by markbjadu** [jadu/pulsar#1017]
A long message needs wrapping 

1. Add bartec test integration to CMS
2. Add a bartec bins at property IC to the page 
3. On the page set-up of the IC once adding the page to the form enter invalid data and save.
4. Submit the form
5. Go to received form log failed IC question details.
6. Load the message for the failed IC.

![Screenshot 2019-09-05 at 10 49 08](https://user-images.githubusercontent.com/6906173/64334283-1c82eb80-cfd0-11e9-8d05-7cf3cf6ed658.png)

A long message should be wrapped in the light box.

**Desktop (please complete the following information):**
 - OS: mac OS 10.14.6
 - Chrome latest
 - 76.0.3809.132 (Official Build) (64-bit)

NB: I have obscured the token so it can't be used.

**Comment by Stanton** [comment]
@markbjadu Can you provide a test environment for this issue? (feel free to send me a Slack message if it's an internal server)

**Comment by Stanton** [comment]
Should be resolvable by developer using the `.u-word-break` utility class.
