### ISSUE TITLE
Add Jadu Deployer colour palette/logo/favicon/integrations logo

### ISSUE THREAD

**Issue by skmetaly** [jadu/pulsar#1024]
**Is your feature request related to a problem? Please describe.**
Jadu Deployer has a new colour palette and logo which currently are not available in the Pulsar library

**Describe the solution you'd like**
- Add a new palette branding with the following colours:

```
                darkest:     rgb(46, 54, 112),
                dark:        rgb(61, 71, 150),
```
- Add the Jadu Deployer logo branding with favicon as well
- An integration logo for Deployer as well

**Describe alternatives you've considered**
- Could do for now with only favicon and integration logo, even if the work isn't yet merged into Pulsar since we can add/override stylings in the project

**Additional context**
- Added screenshots and the .svg with the logo

![deployer-icon](https://user-images.githubusercontent.com/2950961/65674096-afa1c500-e054-11e9-866b-f40947322de1.png)

[deployer-logo.svg.zip](https://github.com/jadu/pulsar/files/3656910/deployer-logo.svg.zip)

![deployer-dashboard](https://user-images.githubusercontent.com/2950961/65674215-db24af80-e054-11e9-9a29-5faa4d40408e.png)

![deployer-login](https://user-images.githubusercontent.com/2950961/65674282-f8f21480-e054-11e9-8415-03e6c9f5907e.png)

Thank you!

**Comment by Stanton** [comment]
@skmetaly While the main brand images are white-on-transparent, for some favicon/device icon variations we need a background colour, I'm going for white-on-purple unless you have a different preference?

![android-chrome-512x512](https://user-images.githubusercontent.com/18653/65699192-a117d580-e075-11e9-8456-98799348feef.png).

The pipeline I have in place at the moment generates all images from the source, it may be more appropriate for smaller versions (probably anything under 50x50, we go down to 16x16) to simply use the rocket motif alone without the surrounding A or smoke. Lee would have to create you a separate SVG for these if required.

**36x36**
![android-chrome-36x36](https://user-images.githubusercontent.com/18653/65699434-01a71280-e076-11e9-8f83-3a0a9785a046.png)

**16x16 on a black bg for contrast**
![Screenshot 2019-09-26 at 15 54 55](https://user-images.githubusercontent.com/18653/65699473-0ff52e80-e076-11e9-91f5-c46b03eb0253.png)

**Comment by skmetaly** [comment]
thanks @Stanton! white-on-purple is what I was hoping for, looks good :) Think it's good for now, can't think of any use case for now for super small icons, but i'll let you know

**Comment by Stanton** [comment]
> thanks @Stanton! white-on-purple is what I was hoping for, looks good :) Think it's good for now, can't think of any use case for now for super small icons, but i'll let you know

They're your browser favicons :)
