### ISSUE TITLE
Update datatables length select styles to be more inline with pulsar select styles

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#1034]
Currently the DataTables length select control uses browser default styling (see screenshot). This needs updating and brining inline with Pulsars select styles.

![Screenshot 2019-10-24 at 13 41 42](https://user-images.githubusercontent.com/756393/67486521-1a4e1c80-f664-11e9-9b66-dbdd36bb3c79.png)

**Comment by Stanton** [comment]
Fixed in #1136
