### ISSUE TITLE
Drop Down menu is outside the area that is intended for at reduced size. 

### ISSUE THREAD

**Issue by markbjadu** [jadu/pulsar#1042]
Drop Down menu is outside the area that is intended for at reduced size. 

1. Make the chrome window to the size attached image
2. See the dropdown menu for field is outside of the intended area this also happens after refreshing the page.

Drop down menu should remain in intended area 

![Screenshot 2019-11-06 at 15 08 59](https://user-images.githubusercontent.com/6906173/68385543-f0135900-0151-11ea-851c-f9265422556c.png)

![Screenshot 2019-11-07 at 11 39 48](https://user-images.githubusercontent.com/6906173/68386183-682e4e80-0153-11ea-927a-15756f65823f.png)

 - OS: mac OS 10.15.1
 - Browser Chrome latest
- Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by Stanton** [comment]
Issue to be resolved in the XFP repository.

1. Add `component.repeater.scss` in `xforms.scss`
2. Run `grunt sass` in terminal
3. Test & Commit
