### ISSUE TITLE
Creating a field with no content in the field is save as (empty).

### ISSUE THREAD

**Issue by markbjadu** [jadu/pulsar#1045]
Creating a field with no content in the field is save as (empty).

1. Go to /jadu/xforms2/paybridge/settings?pspID=4 - Must be GovUK Pay adapter and with metadata fields fix in XFP.
2. Click on 'Add'
3. Save it without entering any text 
4. See that it saves as (empty)

The field is saved as (empty).
Should be flagged as required.

OS: mac OS 10.15.1
Browser Chrome latest
Version 78.0.3904.97 (Official Build) (64-bit)

![Screenshot 2019-11-07 at 15 10 01](https://user-images.githubusercontent.com/6906173/68401040-f49b3a00-0170-11ea-8e15-042f630aaaf9.png)

**Comment by Stanton** [comment]
Required fields not currently supported by the Repeater component, we will progress this as a feature request.
