### ISSUE TITLE
Update documentation with browser and screen reader version support

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#1051]
Perform and log lexicon testing results with common browser, screen reader and OS combinations.

For example:

Win7 IE11 JAWS
Win7 IE11 NVDA
Win10 EDGE JAWS
Win10 EDGE NVDA
Win10 EDGE Narrator
WIn10 Chrome JAWS
Win10 Chrome NVDA
Win10 Chrome Narrator
WIn10 Firefox JAWS
Win10 Firefox NVDA
Win10 Firefox Narrator
Mac OS Voiceover
iOS Voiceover
Android

**Comment by Stanton** [comment]
Presuming out of date
