### ISSUE TITLE
Stepped progress bar has invalid markup

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#1066]
Stepped progress bar has invalid markup.

The following aria attributes are not valid on a `ol` element:

- `role="progressbar"`
- `aria-valuenow`
- `aria-valuemin`
- `aria-valuemax`

Potential to either retire the component or to move aria attributes to a wrapping `div`.

**Comment by Stanton** [comment]
Happy for this to be retired, only one UI uses this pattern in CMS that I'm aware of.

**Comment by jamesjacobs** [comment]
Resolved by #1104
