### ISSUE TITLE
Create new 'status indicator' component

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#109]
Not quite a label, not quite a badge, but some form of indicator which can indicate online/offline or active/inactive.

- [x] Helper
- [x] Unit tests
- [x] Documentation
- [x] Lexicon

**Comment by Stanton** [comment]
http://codepen.io/pulsar/pen/mPrvqZ

**Comment by Stanton** [comment]
![screen shot 2016-03-14 at 15 28 37](https://cloud.githubusercontent.com/assets/18653/13749470/77d6d908-e9f9-11e5-9757-70604a689e32.png)

**Comment by jamesjacobs** [comment]
:+1: 

Small point - the red doesn't look like the default "danger" red.

**Comment by Stanton** [comment]
It's not just yet, will tweak colours when I come to implement, the default danger red seemed really close to the default green when on a small element like this, though that may only be an issue when they're close together...

**Comment by Stanton** [comment]
![screen shot 2016-03-14 at 15 33 27](https://cloud.githubusercontent.com/assets/18653/13749625/323844b2-e9fa-11e5-8be2-871eebbaa602.png)

**Comment by Stanton** [comment]
Switched back to default palette, now they're spaced out slightly from when I first coded them up they're fine :) 
![screen shot 2016-03-14 at 15 35 09](https://cloud.githubusercontent.com/assets/18653/13749705/6dde3f26-e9fa-11e5-8f62-2466b951905e.png)
