### ISSUE TITLE
Panel helper contains invalid aria attribute if panel title omitted

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#1131]
**Describe the bug**
If a panel is used without a title, the wrapping `section` element still uses `aria-labelledby` but there is no title which uses the reference.

**To Reproduce**
```
 {{
    html.panel({
        'class': 'panel--warning u-margin-top-none',
        'body': 'The limit for the number of live Galaxies sites allowed by the license has been reached',
        'icon': 'info-sign'
    })
}}

<section class="panel panel--warning u-margin-top-none" aria-labelledby="guid-170767129">
    <i aria-hidden="true" class="icon-info-sign panel__icon"></i>
    <div class="panel__body">The limit for the number of live Galaxies sites allowed by the license has been reached</div>
</section>
```

**Expected behavior**
To be discussed, either omit the aria attribute linking to the title, or change the guid to be on the panel body if no title is present.

**Screenshots**
![Screenshot 2020-02-06 at 10 28 13](https://user-images.githubusercontent.com/18653/73928671-69465780-48cb-11ea-9f0d-6190efff1e67.png)

**Comment by jamesjacobs** [comment]
Fixed by #1134
