### ISSUE TITLE
Repeater issues

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#1146]
1. When the number of saved rows match the max entries setting on page load, the Add button should be disabled and isn't
2. On page load with more than one saved row, clicking 'Edit' for the first row opens the form showing the value for the last row. Weirdly, cancelling the edit and doing it a second time works fine

Reported by @james-manley 

XFP-3934
XFP-3936

**Comment by mikedevelops** [comment]
I can take a look at this @Stanton this week hopefully, I'd like to do https://github.com/jadu/pulsar/issues/1147 as part of it too as it routinely makes me anxious 😄

**Comment by Stanton** [comment]
Branch `1146_repeater`

**Comment by mikedevelops** [comment]
Fixes:
https://github.com/jadu/pulsar/issues/1147
https://github.com/jadu/pulsar/issues/1150

**Comment by jamesjacobs** [comment]
Fixed by #1238
