### ISSUE TITLE
Remove the QueryService and Update the Repeater

### ISSUE THREAD

**Issue by mikedevelops** [jadu/pulsar#1147]
**Is your feature request related to a problem? Please describe.**
The QueryService was added by me when I was clearly in a strange place. I for some reason (maybe too much coffee) Implemented a basic jQuery like DOM lookup service with caching. This was totally unnecessary. I should have just used jQuery or regular methods. It will be so confusing to anyone that tries to work on a component with this in.

**Describe the solution you'd like**
Kill it with fire.

**Comment by jamesjacobs** [comment]
Fixed by #1238
