### ISSUE TITLE
Review use of JS tabs in secondary navigation

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#1182]
The lexicon and possibly some products use JS styles tab changes in the secondary navigation. Due to the position of `main` which is currently inside of a tab panel, this creates issues as all tabs are present in the dom on page load and therefore we have potentially many `main` elements where JS tabs are used.

Review the need for JS tabs. If still required we need to address the `main` issue and also look at the suitability of our tabs and the aria `role="tablist"` spec.

**Comment by Stanton** [comment]
> possibly some products

Both CMS and XFP use JS tabs, and change here would need long-term planning, We can retire JS tabs however we'd still need to support them and provide an intermediate solution to support them long term, possibly by swapping out the `main` elements when JS tabs are used.

**Comment by Stanton** [comment]
@jamesjacobs Do you reckon we resolved this with the recent changes to js tabs?
