### ISSUE TITLE
Investigate use of `aria-invalid` on page load

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#1184]
Site Improve flags this as an error. Investigate our use, could potentially be only suitable when added via JS when form is submitted by AJAX.

![image](https://user-images.githubusercontent.com/756393/77065984-34551680-69da-11ea-82fd-ddda5d6c8817.png)

**Comment by Stanton** [comment]
> This ARIA attribute has to be set / turned on programmatically. It should not be set to “true” before input validation is performed or the form is submitted

**Comment by jamesjacobs** [comment]
Sure, my main concern/confusion is if it's valid to use it on page load following a traditional form submission (and page reload) or if it should only be used when an "invalid" value is detected by JS or via a form submitted via ajax (with no page load).

Most of the use examples I can find use JS:
https://www.w3.org/WAI/WCAG21/working-examples/aria-invalid-data-format/
https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA21.html

Though the docs don't mention scripting: https://www.w3.org/TR/wai-aria-1.1/#aria-invalid

Also GDS do not appear to use it: https://design-system.service.gov.uk/components/text-input/

**Comment by Stanton** [comment]
I think this is our key bit of information:

> This ARIA attribute has to be set / turned on programmatically. It should not be set to “true” before input validation is performed or the form is submitted. Setting aria-invalid to “false” is the same as not placing the attribute for the form control at all. Quite understandably, nothing is conveyed by assistive technology to users in this case.

I think we can assume 'programatically' to mean 'set by JavaScript', and if we're setting this with Twig it will fall under the category of 'nothing is conveyed by assistive technology to users in this case', a brief test seems to indicate that the error reported in AT tools don't disappear on form submit.

Suggested way forward to be remove all `aria-invalid` support from the Twig helpers.
