### ISSUE TITLE
Range width changes on focus

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#1226]
**Describe the bug**
On focus, the width of the range slider changes.

**To Reproduce**
1. Focus on a range slider

**Expected behavior**
Width stays the same

**Screenshots**
![range](https://user-images.githubusercontent.com/9383439/81932666-0825d280-95e4-11ea-82c7-9cdeab0fee65.gif)

**Comment by Stanton** [comment]
This is expected behaviour to accommodate the focus outline.

**Comment by jackbentley** [comment]
I'm not sure this is intentional. And if it is, it's not good.

The selector clearly jumps when focused:
![range-jump](https://user-images.githubusercontent.com/9383439/82922462-86ce2880-9f71-11ea-8d82-ef6d47876e3c.gif)

The width and centre lines of the selector aren't aligned:
<img width="292" alt="Screen Shot 2020-05-26 at 16 41 08" src="https://user-images.githubusercontent.com/9383439/82922534-a2393380-9f71-11ea-869d-66b5a56dbce8.png">
(center lines are dashed; range limits are solid)

This could become particularly problematic if a scale was applied:
<img width="117" alt="Screen Shot 2020-05-26 at 16 50 29" src="https://user-images.githubusercontent.com/9383439/82922660-cc8af100-9f71-11ea-95bb-e796e9a8db1c.png">
<img width="121" alt="Screen Shot 2020-05-26 at 16 50 21" src="https://user-images.githubusercontent.com/9383439/82922665-cd238780-9f71-11ea-9eb8-471c3660816e.png">

> "Why can't I select 10?"
> "When I select 10 it changes to 9.5"
> "When I select 9 it changes to 8.5" (etc..)

It looks like a 5px left and right padding is adding on focus. This should always be present.

Additionally, it could be argued that the focus border around the entire input isn't required. As the end-user is only really interested in the selector it's self. When you click on the input, the selector will move to the position you clicked. If you're focused and use the left and right arrows, only the selector will move.
