### ISSUE TITLE
Dropdown receives unnecessary top margin

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#1227]
**Describe the bug**
The alignment of the dropdown is wrong. The dropdown received unnecessary top margin which misaligns it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Render a dropdown

**Expected behaviour**
The dropdown is rendered level with the label - just like a text input.

**Screenshots**
<img width="552" alt="Screen Shot 2020-05-15 at 11 16 01" src="https://user-images.githubusercontent.com/9383439/82039943-a32eb300-969d-11ea-90c1-540161e12bdb.png">
<img width="553" alt="Screen Shot 2020-05-15 at 11 10 50" src="https://user-images.githubusercontent.com/9383439/82039740-5e0a8100-969d-11ea-91af-1d34e2042ea5.png">

**Comment by Stanton** [comment]
Please provide markup for the first element, or details of where to find it in product. Examples in documentation don't demonstrate this positioning.

**Comment by jackbentley** [comment]
It's visible in the Pulsar docs: https://pulsar.docs.jadu.net/forms/choice

I think the additional margin is intended to make the radio buttons text line up with the question text:

![Screen Shot 2020-05-27 at 17 03 04](https://user-images.githubusercontent.com/9383439/83044567-425b8f00-a03c-11ea-9ccd-7884a3c63829.png)

Note that choice blocks are also misaligned:

![Screen Shot 2020-05-27 at 17 02 55](https://user-images.githubusercontent.com/9383439/83044646-5bfcd680-a03c-11ea-9713-a5aff862923f.png)

**Comment by Stanton** [comment]
Ah ok, original issue didn't mention this was a choice dropdown over a regular select/select2 but yeah, there are a number of vertical alignment issues at play which will need mopping up.

**Comment by Stanton** [comment]
Holding off on looking at this until flatcap is merged into develop
