### ISSUE TITLE
Outline button changes height (and style) when clicked

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#1230]
**Describe the bug**
When clicking an outline button, it changes height can cause other elements in the DOM to shift. Additionally, the style isn't retained on focus styling.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click an outline button

**Expected behaviour**
The button should not change height when clicked and other elements on the page should not shift. The button should retain the "outline" style but with the appropriate focus colours when focused.

**Screenshots**
See the (presumably) 1px change on click causing the below elements to shift.

![button-jump](https://user-images.githubusercontent.com/9383439/82093051-47424980-96f2-11ea-9ea5-25d82aaeff8e.gif)

See the focus style does not represent an outline button.

![Screen Shot 2020-05-15 at 21 24 48](https://user-images.githubusercontent.com/9383439/82093221-a1430f00-96f2-11ea-8745-bd4546ffbc19.png)

**Comment by jackbentley** [comment]
They're also inconsistent with the new header toolbar buttons (the border is removed on one but not the other).

It also seems like focusing on the Menu button causes the search bar to move left/right by one pixel.

![Screen Shot 2020-05-20 at 18 43 50](https://user-images.githubusercontent.com/9383439/82479190-f3f14200-9ac9-11ea-9a25-01d9420f1058.png)
![Screen Shot 2020-05-20 at 18 43 38](https://user-images.githubusercontent.com/9383439/82479196-f5226f00-9ac9-11ea-8ed0-20bbcc5510af.png)

**Comment by Stanton** [comment]
Fixed by #1234 

![toolbarfocus](https://user-images.githubusercontent.com/18653/83000964-fd673680-a002-11ea-9f92-b22c87c7c87e.gif)

Outline buttons will not maintain their outline border when focused, they will adopt a singular consistent focus style.
