### ISSUE TITLE
Clicking a toggle too fast causes focus style to be lost

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#1232]
**Describe the bug**
Clicking a toggle button too fast causes the focus style to be lost. **The toggle is still in focus, however.**

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on a toggle switch fast

**Expected behaviour**
Focus style stays in place.

**Screenshots**
![toggle-focus](https://user-images.githubusercontent.com/9383439/82480063-26e80580-9acb-11ea-82c8-4713cc92558b.gif)

**Comment by Stanton** [comment]
Issue not present on #1211
