### ISSUE TITLE
Flash message covers menu

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#1233]
**Describe the bug**
When a flash message is on-page, it covers the menu

**To Reproduce**
1. Cause a flash message to appear
2. Open a menu item

**Expected behavior**
The menu appears over the flash message

**Screenshots**
<img width="1015" alt="Screen Shot 2020-05-21 at 10 51 43" src="https://user-images.githubusercontent.com/9383439/82547903-5f7ef200-9b52-11ea-9af3-30ff8ba0efd0.png">

**Comment by Stanton** [comment]
Fixed by #1234
