### ISSUE TITLE
Table THs should use scope="col"

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#1343]
Table headers (`thead th`'s) should use the `scope="col"` attribute to help user of assistive technology identify columns and potentially the difference between row headers and column headers.

Table and datatable helpers to handle where possible.

Related links:
https://www.w3.org/WAI/tutorials/tables/one-header/
https://www.w3.org/TR/WCAG20-TECHS/H63.html

Documentation examples will need to include and cover this.

**Comment by Stanton** [comment]
Is this breaking any WCAG criteria or is it an enhancement/best practice? (as in, does this need adding to the platform accessibility statement?)

**Comment by jamesjacobs** [comment]
@Stanton An enhancement. It's not a requirement, unless we have a mix of column and row headers in a table (we don't to my knowledge).
