### ISSUE TITLE
Utility classes should have the highest specificity

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#138]
The specificity of utility classes needs increasing as currently they can be overridden by more specific selectors which defeats the purpose of them really.

Could chain the selectors with themselves to specificity++ if `!important` is too heavy handed, although if there is anywhere `!important` should be used, it's in utility classes.

**Comment by Stanton** [comment]
Interesting note on how Bootstrap deals with specificity in http://v4-alpha.getbootstrap.com/components/utilities/

> Sometimes contextual classes cannot be applied due to the specificity of another selector. In some cases, a sufficient workaround is to wrap your element’s content in a <div> with the class.

**Comment by Stanton** [comment]
Recent utility classes take advantage of immutability to make sure they can't be overridden, we'll mop up any older classes on an 'as required' basis to avoid implementing breaking changes.
