### ISSUE TITLE
Select2 min-width can cause reflow issues when used inside containers

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#1387]
**Describe the bug**
When a select2 component is used inside a container or context which adjust the starting position of the element, the min-width of 260px may break the layout.

Observable in `XFP-XFO-184` when choosing conditional logic type.

**Expected behavior**
Select2 components should be as responsive as regular selects and not force a minimum width.

**Screenshots**
![Screenshot 2021-03-05 at 11 21 23](https://user-images.githubusercontent.com/18653/110109489-702ceb80-7da5-11eb-88f1-ef9e04a89fd5.png)

**Comment by jamesjacobs** [comment]
Potentially an XFP or P11 specific rule as I can't see this rule in the P12 lexicon.
