### ISSUE TITLE
form.choice not applying class to options

### ISSUE THREAD

**Issue by Hodgy** [jadu/pulsar#168]
passing `[{"label":"Full Editor - Edited","value":"1","class":"js-addButton-presets"},{"label":"Default Editor","value":"2","class":"js-addButton-presets"},{"label":"Full editor no tables","value":"4","class":"js-addButton-presets"}]` into the `options` of a `form.choice`

but it’s not setting the class on the checkbox inputs
if i change it to be `name` instead of `class` it’s adding it

**Comment by Stanton** [comment]
Specific issue for `form.choice` is with the radio_inline and checkbox_inline helpers.

Normally, `class` arguments are applied to the parent `form__group` wrapper, but when using `bare` this element doesn't exist and classes are simply not used. All form helpers should probably pass classes to the related `input` element if using `bare`.

This will need implementing for all form helpers, but for this ticket we'll just sort `form.choice` so @Hodgy can finish his UI.
