### ISSUE TITLE
Form label 'required' asterisk disappearing after hover on / off

### ISSUE THREAD

**Issue by langy** [jadu/pulsar#18]
also observed position change of entire label when moused out, possibly caused by disappearing asterisk

**Comment by Stanton** [comment]
![required-fields_360 gif png](https://cloud.githubusercontent.com/assets/18653/12779086/113a3510-ca5e-11e5-9432-e81e3a66d753.gif)

**Comment by langy** [comment]
Turns out this is caused by the Prototype.js library that's used on this page to enable legacy lightbox functionality. Closing.
