### ISSUE TITLE
Add ESRI logo for use on CMS integrations page

### ISSUE THREAD

**Issue by langy** [jadu/pulsar#232]
An image needs adding in order to display a logo for the ESRI integration as per CMS-3443

**Comment by Stanton** [comment]
@langy  Would suggest we find a way for these to be part of the integration code, rather than in the Pulsar repository.

**Comment by langy** [comment]
Argh, okay. Had a look at the existing ones and all their images were inside this repo so figured I'd follow suit! Closing.
