### ISSUE TITLE
Add 'disabled' option to inline navigation / tabs

### ISSUE THREAD

**Issue by langy** [jadu/pulsar#233]
Tabs can be made active, or hidden, but not disabled. It would be nice to be able to inform users of all navigation options from the get-go but just disabling those they can't access yet, rather than magically introducing them.

Example:
![image](https://cloud.githubusercontent.com/assets/713141/16149300/c36e9120-3487-11e6-95d6-93f1edce64db.png)

**Comment by Stanton** [comment]
@langy Did you do this work? Did I see it in the XFP demo you did recently?

**Comment by langy** [comment]
@Stanton No not yet, that was just a mock-up. It'll be coming soon though!
