### ISSUE TITLE
Table no results action button text colour is incorrect

### ISSUE THREAD

**Issue by tompedals** [jadu/pulsar#257]
![screen shot 2016-07-25 at 10 03 09](https://cloud.githubusercontent.com/assets/6132043/17095977/1e8ebcd0-524f-11e6-935b-bc5f04a58e01.png)

The button text colour should be white but is being overridden by some generic table link styles.

**Comment by Stanton** [comment]
@tompedals Fixed in develop

**Comment by Stanton** [comment]
Released in `6.7.1`
