### ISSUE TITLE
Create new `form.choice()` helper

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#27]
Todo:
----

- [x] Documentation
- [x] Unit tests
- [x] Helper code
- [x] Styles

Initial documentation:
----
# Choice

Displayed as a question with multiple answers, each of which has it's own label and can allow either singular (checkboxes) or multiple (radios) choice.

By default, the choice helper will will automatically adhere to Pulsar's form styleguide by switching to a [select2](select2.md) element if more than 5 options are provided.

## Example usage

```twig
{{
    form.choice({
        'label': 'Do you like me?',
        'options': [
            {
                'label': 'Yes',
                'value': '1'
            },
            {
                'No': '0',
                'value': 'No'
            },
            {
                'label': 'Maybe',
                'value': '¯\_(ツ)_/¯'
            }
        ]
    })
}}
```

## Options

Option     | Type   | Description
---------- | ------ | -------------------------------------------------------
autoswitch | bool   | Whether the control shoud use a  select2 if more than 5 options are provided. Default `true`
class      | string | A space separated list of class names
help       | string | Additional guidance information to be displayed next to the input
label      | string | Text for the main `<label>` companion element
options    | array  | An array of option hashes that will be passed to the [checkbox](checkbox.md) or  [radio](radio.md) helper, see their documentation for specifics
required   | bool   | Visually indicates that the field must be completed, will not be displayed if `type` is radio as they're implicitly required
type       | string | Which type of control to use `checkbox (default)` or `radio`

**Comment by mgduk** [comment]
Why not make the default value for `type` to be `auto`, then you can lose the `autoswitch` option

**Comment by Stanton** [comment]
@mgduk `type` switches between `checkbox` and `radio`, `autoswitch` switches between the configured `type` and `select2` based on the number of options

**Comment by mgduk** [comment]
ah yes — sorry, didn't read `type` properly.

Might it be better to configure based on semantics rather than on mechanism? 
e.g.
`multiple` (boolean) (whether the user can select multiple options)
`extent` (`auto`, `few`, `many`)

Then the logic for the view is something like this:
```
if $extent == auto
    if $number_of_options <= 5
        $extent = few
    else
        $extent = many

if $extent = few
    if $multiple then render radio buttons
    else render checkboxes
else if $extent = many
    render select[multiple=$multiple]
```

(‘extent’ may not be the best word… but I couldn't think of a better one)

This approach avoids mixing the presentation with the logic. By defining the _semantics_ of what's required, the UI is free to make its own choice of how best to present that. 

If you configure with options like `checkbox` you're tightly coupling the configuration with the presentation form, and mixing your concerns.

**Comment by Stanton** [comment]
Great points, much prefer the `multiple` option, not sure about `extent` as the user config side of that doesn't feel obvious...

**Comment by mgduk** [comment]
Yeah, I haven't been able to think of a concept that really encapsulates what I'm trying to get at with `extent`. It's really size/scale thing — 
“optimise UI for a large number of items” —> select box
“optimise UI for a small number of items” —> checkboxes

Generally speaking, you'd want it left as `auto`, unless there's a really good reason for needing a select box with two items. So it's very much a Power User configuration option. Which may be an argument for not needing it to be _too_ easily understandable ;-)

**Comment by Stanton** [comment]
I think having the default as simply `'auto-optimise': 'true', with the ability to disable if necessary should work...

**Comment by mgduk** [comment]
“Optimise” is good. 

You can get all that logic, with proper semantic separation with:
```
multiple: [true, FALSE]
optimise: [AUTO, few, many]
```
(or possibly `optimise: [AUTO, small, large]`)

**Comment by Stanton** [comment]
going for:

Option   | Type   | Description
-------- | ------ | -------------------------------------------------------
optimise | string | `auto` (default) use a select2 element if number of `options` is greater than 5<br />`few` force the use of checkboxes/radios regardless of the number of options  <br />`many` force the use of select2 regardless of the number of options

**Comment by mgduk** [comment]
Looks great.

Just checking that Pulsar does use British English (“optimise”) and not American English (“optimize”) everywhere else?

**Comment by Stanton** [comment]
🇺🇸 Changed in PR
