### ISSUE TITLE
Potentially use yellow/cream rather than blue for dragging/previewing highlight colour

### ISSUE THREAD

**Issue by langy** [jadu/pulsar#286]
When dragging elements on to a 'drop zone', or when previewing a content change in-context, we tend to use a light blue background colour to highlight these areas. It needs trying first to see how it looks, but I feel a light yellow would work better here.

**Comment by Stanton** [comment]
Worth adding more state colours to the palette and using them here https://github.com/jadu/pulsar/blob/develop/stylesheets/_utility.sortable.scss
