### ISSUE TITLE
IE8 doesn't respect form__group widths

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#293]
Due to `.form__control:not(.checkbox):not(.radio):not(.file)`

![screen shot 2016-08-24 at 16 00 53](https://cloud.githubusercontent.com/assets/756393/17935637/fa545b90-6a13-11e6-86f7-50b9d54bc150.png)

**Comment by langy** [comment]
Appears fine on latest develop branch? Maybe one of the scripts hadn't finished loading, or failed? As it will rely on Selectivizr to work. Can't tell if there were errors/warnings as the bottom of the browser window is cropped.

<img width="1409" alt="screen shot 2016-09-26 at 12 03 14" src="https://cloud.githubusercontent.com/assets/713141/18832070/419833f0-83e1-11e6-9d51-fe8f43d94ac7.png">

**Comment by jamesjacobs** [comment]
CXM doesn't use Selectivizr but as IE8 support is only functional I'm happy to close.
