### ISSUE TITLE
Decide whether or not various overrides are needed anymore

### ISSUE THREAD

**Issue by langy** [jadu/pulsar#313]
There are a number of overrides inside the `_override.shame.scss` file that are quite broad in terms of what elements they're targeting.

This is causing some funky layout issues to occur (see attached screenshot).

The lines needing review are potentially from an old iteration of the Q software, specifically:
https://github.com/jadu/pulsar/blob/develop/stylesheets/_override.shame.scss#L62-L177

![image](https://cloud.githubusercontent.com/assets/713141/18355875/83e070ea-75e2-11e6-843e-706a3c2fa7a6.png)

**Comment by langy** [comment]
![image](https://cloud.githubusercontent.com/assets/713141/18477344/43b8b8a6-79c5-11e6-8260-07418b02b06a.png)

**Comment by jamesjacobs** [comment]
Fixed in https://github.com/jadu/pulsar/pull/522
