### ISSUE TITLE
Change the URL for tab navigation 

### ISSUE THREAD

**Issue by ramakrishnab** [jadu/pulsar#333]
```
 When I navigate to a page with 3 tabs
  And I make a post action on tab 1
 Then I see the route is changed in the URL
 When I click on the tab 2
 Then I should see the corresponding URL
  But I see the route is not changed on tab navigation until another post request is made/page refresh.

```

**Comment by ramakrishnab** [comment]
![screen shot 2016-09-26 at 12 30 01](https://cloud.githubusercontent.com/assets/18738189/18832716/feb6f914-83e4-11e6-8835-f204043a5737.png)

**Comment by Stanton** [comment]
@ramakrishnab Work completed for this request, awaiting peer review by the Pulsar team. Should be ready to test in Continuum CMS next week.
