### ISSUE TITLE
Label text colour should be immutable 

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#379]
For example, when a label is in a disabled table row, the text is overridden to grey resulting in the label not meeting AA.

![screen shot 2016-10-23 at 09 13 52](https://cloud.githubusercontent.com/assets/756393/19624903/0febc828-9901-11e6-909c-1bb9fbf3c26e.png)

**Comment by Stanton** [comment]
There's a possibility this may have been resolved elsewhere, I've created a visual test with the following markup:

```
<table class="table">
    <tr class="is-disabled">
        <td>
            <!-- labels in here -->
        </td>
    </tr>
</table>
```

Which results in the following output

<img width="224" alt="screen shot 2016-11-13 at 21 29 59" src="https://cloud.githubusercontent.com/assets/18653/20249037/c7e04196-a9e8-11e6-83b5-bf1d5b3be031.png">

So I'm unable to replicate the posted issue with `label--warning` or any other labels.

I'll still create a pull request for the visual diffs and lexicon updates, so don't close this ticket for now.
