### ISSUE TITLE
Link buttons with is-disabled class have incorrect text colour

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#382]
![screen shot 2016-10-23 at 11 45 53](https://cloud.githubusercontent.com/assets/756393/19625671/d643de4c-9916-11e6-9d80-70d2bcd21429.png)

Caused by  https://github.com/jadu/pulsar/blob/develop/stylesheets/_utility.states.scss#L83

**Comment by Stanton** [comment]
| Button 'family' | Impact |
| -------------- | ------- |
| Normal buttons                   | ⛔️ `disabled` states |
| Outline buttons                   | ✅ Not affected |
| Disabled buttons                | ⛔️ `base`, `active`, `disabled` states |
| Disabled outline buttons    | ✅ Not affected |

## Normal `button` vs `link`

<img width="1374" alt="screen shot 2016-10-23 at 21 03 40" src="https://cloud.githubusercontent.com/assets/18653/19629129/a59f5d76-9965-11e6-8d9e-f857271a9643.png">

## Disabled `button` vs `link`

<img width="1371" alt="screen shot 2016-10-23 at 21 09 15" src="https://cloud.githubusercontent.com/assets/18653/19629136/c47cc0b2-9965-11e6-9246-f7f7fbd42d1a.png">
