### ISSUE TITLE
Main nav is 'draggable' on mobile devices

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#386]
Most notable on Android, navigation can be dragged by around 60%, affects both Samsung Internet and Chrome.

iOS devices can be dragged by approx 4 pixels, hardly noticeable but still there.

![img_5720](https://cloud.githubusercontent.com/assets/18653/19643299/88dfb0d8-99e1-11e6-9bf9-8066c8c83da1.gif)

Issue observed in:

- [x] Mobile Safari
- [x] Samsung Internet

**Comment by Stanton** [comment]
Issue deliberately reintroduced in 6.14.1 as it was causing a critical IE bug.

**Comment by Stanton** [comment]
@nvasileiadis There's an `awaiting review` label on this one but no related pull request?

**Comment by nvasileiadis** [comment]
IE9
![image](https://cloud.githubusercontent.com/assets/1425876/21841739/85e625aa-d7db-11e6-8e09-81c07b88b178.png)

IE8 (IE9 Compatibility mode)
![image](https://cloud.githubusercontent.com/assets/1425876/21841780/add53fc4-d7db-11e6-99f3-fc7573299795.png)
