### ISSUE TITLE
Settings layout desktop view broken in IE9

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#435]
Issue seems to be present at tab `6.8.4` so there's a chance this never worked...

![settingsie9](https://cloud.githubusercontent.com/assets/18653/20919654/d7583274-bb94-11e6-905f-eba1a57fef08.gif)

**Comment by langy** [comment]
There was some IE-specific Sass that fixed this when originally used in
XFP's Publish tab layout, maybe it got missed with the migration into
Pulsar.
