### ISSUE TITLE
Primary navigation not hiding correctly in responsive mode

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#448]
Identified by @nvasileiadis here: https://github.com/jadu/pulsar/pull/446#issuecomment-270692651

Issue is present on develop and seems to affect all IE versions.

![nav-issue](https://cloud.githubusercontent.com/assets/18653/21697135/ed46ba22-d388-11e6-9ce5-c15fe63dd9e2.gif)

**Comment by Stanton** [comment]
First suspect would be 8e272edde0059837a90de63313d0e1986e79553b

**Comment by nvasileiadis** [comment]
There is an issue with the toggleClass on IE10. ".open-nav" in body isn't initialized.
