### ISSUE TITLE
In Mobile the "Back to the Top" Arrow isn't Working

### ISSUE THREAD

**Issue by nvasileiadis** [jadu/pulsar#458]
![d1778e546ac046c58fba8a237a6daaee](https://cloud.githubusercontent.com/assets/1425876/21811352/4ff49b78-d747-11e6-8bd6-19b6a8fa294b.png)

**Comment by nvasileiadis** [comment]
http://prntscr.com/dtuk41

**Comment by Stanton** [comment]
@nvasileiadis Is this still blocked?

**Comment by nvasileiadis** [comment]
@Stanton basically the fix was included in #459. The problem existed in the specific branch, it wasn't possible to replicate anywhere else.
