### ISSUE TITLE
Datatables don't respond correctly when table width is greater than browser window

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#474]
Issue is present when tables have a reasonable number of columns.

![datatables issue](https://cloud.githubusercontent.com/assets/756393/22471921/e980769c-e7cb-11e6-97df-36b5cb01f270.gif)

**Comment by jamesjacobs** [comment]
Issue seems to be down to `display: table;` being set at desktop width on `.tab__inner`.

**Comment by Stanton** [comment]
Closed by #475
