### ISSUE TITLE
Standard buttons no longer have borders in button group

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#500]
![screen shot 2017-03-07 at 15 58 09](https://cloud.githubusercontent.com/assets/756393/23664932/f8eaeea2-034e-11e7-9a2a-185039ecf612.png)

Other button states seem unaffected.

**Comment by Stanton** [comment]
Can't replicate in `develop` branch, checked in Safari, Chrome & FF.

Closing unless steps for reproducing can be provided.
