### ISSUE TITLE
Tooltips on dropdown menu items don't have proper width

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#591]
When a tooltip is on a dropdown menu item the width isn't calculated correctly:

**inside of dropdown:**
![screen shot 2017-07-21 at 09 36 48](https://user-images.githubusercontent.com/756393/28455866-7a6b0502-6df8-11e7-98e3-8d16907bf9b2.png)

**outside of dropdown:**
![screen shot 2017-07-21 at 09 38 24](https://user-images.githubusercontent.com/756393/28455874-7fb7deb8-6df8-11e7-8396-2baafe2ff820.png)

**Comment by jamesjacobs** [comment]
Taken a look at this. There doesn't seem to be an easy fix.

Solutions explored:
- an additional wrapper for the tooltip set to `position: relative` (needs core tooltip change and more markup ☹️  )
- set a `min-width` on `.tooltip__inner` (not an option as tooltips could potentially be very short and look odd with too much width if the content doesn't fill)
- setting `position: relative` on `.tooltip__inner` doesn't have any effect

Tooltips can already accept html, so as a workaround devs can add a wrapper to the tooltip content with a custom class/style to increase the width so a broader fix may not be needed.

Would be good to get another pair of 👀  on this too.

**Comment by Stanton** [comment]
> There doesn't seem to be an easy fix.

![http://33.media.tumblr.com/aebeb686a640493b512c8999881d1fb5/tumblr_njzrzaICmG1s3h43ko1_500.gif](http://33.media.tumblr.com/aebeb686a640493b512c8999881d1fb5/tumblr_njzrzaICmG1s3h43ko1_500.gif)

Adding `data-container="body"`, or `'data-container': 'body'` fixes this issue

> Appends the tooltip to a specific element. Example: container: 'body'. This option is particularly useful in that it allows you to position the tooltip in the flow of the document near the triggering element - which will prevent the tooltip from floating away from the triggering element during a window resize.

So, I think we just document this tooltip requirement with the dropdown documentation?

**Comment by jamesjacobs** [comment]
![desk](https://user-images.githubusercontent.com/756393/28611227-fe15deb6-71e2-11e7-8873-331074856fb1.gif)

Totally. Forgot. About. That.

But yeah I'll add to the dropdown docs.
