### ISSUE TITLE
Resizing textarea breaks column sizing

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#609]
This looks to have been fixed previously with `table-layout: fixed` on `form__group` but removed/commented out in `_structure.forms.scss`.

As `display: table` has been removed to fix `form__groups` in modals, we need to explore an alternative fix (`max-width` perhaps?). Or revert to the old fix and override for `form_group`'s inside modals.

![textarea issue](https://user-images.githubusercontent.com/756393/28964735-f4aa25f6-7905-11e7-93f1-2abc00887ab4.gif)

**Comment by Stanton** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=648253

**Comment by Stanton** [comment]
Simple solution would be to constrain to vertical resize only, and trust that the people implementing the UI are giving enough horizontal space through width modifiers...
