### ISSUE TITLE
One table to rule(set) them all

### ISSUE THREAD

**Issue by langy** [jadu/pulsar#61]
We have many table styles. Some work, some don't. We should settle on one and remove the rest.

To determine which we should move forward with, an audit will need to take place on all existing products, ensuring that nothing breaks (or any breakages get fixed) when we settle on one.

**Comment by Stanton** [comment]
Required utility classes:

* centered
* shrink-to-fit
* monospaced
* no-wrap

**Comment by Stanton** [comment]
Closing this as work was done some time ago to provide new common table styles which would work across newer datatables, as well as legacy table/datagrid based tables.
