### ISSUE TITLE
Masterswitch component doesn't disable active UI when disabled

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#616]
Recent changes in masterswitch have broken some existing functionality.

When the layout is 

```
<form>
   <div class="masterswitch">
      ... content ...
   </div>
   <div class="form__actions">
   ... submit button ...
   </div>
</form>
```

The master switch does not disable the master switch contents when toggling from an enabled MS to a disabled MS.

Disabled (on load) to Enabled  - working
![master switch working](https://user-images.githubusercontent.com/756393/29213697-45e8745e-7e9c-11e7-818b-736844a40cb6.gif)

Enabled (on load) to disabled - not working
![master switch not working](https://user-images.githubusercontent.com/756393/29213707-50443960-7e9c-11e7-9fba-b3ab9e07f88a.gif)

Note - the form actions are outside of the masterswitch so the form can still be saved.

**Comment by Stanton** [comment]
@jamesjacobs Can you supply sample code for this? I'm unable to reproduce the issue in Lexicon (I guess your demo is in CXM because of old toggles)

![masterswitch](https://user-images.githubusercontent.com/18653/29322030-12483c34-81d4-11e7-8c82-07e4ce2c06a5.gif)

**Comment by Stanton** [comment]
Example tested:

```
<div class="masterswitch">
    {{
        form.create()
    }}

    {{
        form.toggle_switch({
            'class': 'masterswitch-control',
            'label': 'Enable masterswitch content',
            'id': 'masterswitch-foo',
            'checked': true
        })
    }}

    <hr />

    <section class="masterswitch-content">
        ....
    </section>
</div>
```

**Comment by Stanton** [comment]
@jamesjacobs Not sure if you saw this as it was while you were on A/L
