### ISSUE TITLE
Meet in the middle with attachment styles and file icons

### ISSUE THREAD

**Issue by mikedevelops** [jadu/pulsar#646]
Merge styling of the DropZone file previews with the current attachment file styling (not sure if this is in core or CXM? But could be core either way).

Marry the current file icon chooser with the MIME-TYPER™ service I put together for the D&D work.

Initially I would like this to be a _minor_ change with no markup changes, but this could be subject to change once the work starts.

**Comment by Stanton** [comment]
Is this still required?
