### ISSUE TITLE
Iterate FlashMessageComponent (v2)

### ISSUE THREAD

**Issue by mikedevelops** [jadu/pulsar#651]
The FlashMessageComponent is incredibly useful, however it's a little rigid in terms of the messages that can be created, I think I can iterate on this to grant a level of customisation so we can create infinite* combinations of system flash messages.

This need has been identified as the CXM case alert flash messages are;
**a)** Persistent (cannot be closed) 
**b)** A different combination of icon and colour than the current FlashMessageComponent supports

I'd like to tackle this in a way that does not break existing implementations of FlashMessages. It could be a candidate of becoming a separate package outside of Pulsar that can be versioned separately, in which case there would be a period of the legacy component and a new version existing at the same time (which could be eventually phased out by creating tickets to do so)

_*within the Pulsar colour & icon palette_

**Comment by Stanton** [comment]
An old idea that never got implemented: https://github.com/jadu/pulsar/issues/88

**Comment by mikedevelops** [comment]
That can certainly be included

**Comment by Stanton** [comment]
@mikedevelops Still required?
