### ISSUE TITLE
Password Strength Checker Component

### ISSUE THREAD

**Issue by nvasileiadis** [jadu/pulsar#661]
A JS component for password strength checks. Taking into account similar parameters to http://www.passwordmeter.com and applying them in a beautiful and UX proper way.

**Comment by jamesjacobs** [comment]
Some thoughts, in no particular order:

- Should be flexible enough to support different options depending on the product
- Should highlight if minimum password criteria was meet along with strength
- Should be as unobtrusive as possible and in line with established Pulsar look and feel
- Should be easy to implement, perhaps just with data attributes for options with sensible defaults
- Should not rely solely on colour as an indicator 

Example of password criteria:
- Min 8 chars
- 1 upper and 1 lowercase character
- 1 special character

**Comment by nvasileiadis** [comment]
![password strength checker](https://user-images.githubusercontent.com/1425876/31285427-28202a32-aab3-11e7-8b5c-904654c0ad8f.png)

**Comment by Stanton** [comment]
I’d say we need to try and find that sweet spot between useful information vs visual noise. At the moment I’d say the ‘redesign’ is too cluttered visually and brings too much of a negative towards the, what should be, simple step of creating a password.

It might be the constraint of Balsamiq that makes the indicators look too strong, but I’d say less emphasis on the indicators, and maybe they should only pull focus when they’re in an error state and blend in more when they’re showing success.

**Comment by nvasileiadis** [comment]
![password strength checker 1](https://user-images.githubusercontent.com/1425876/31331522-8546231e-acda-11e7-942e-05b67af631a9.png)

**Comment by nvasileiadis** [comment]
![password strength checker](https://user-images.githubusercontent.com/1425876/31447499-068cb8a0-ae9a-11e7-9e1b-7a64f8b97448.png)

**Comment by nvasileiadis** [comment]
Maybe food for thought...
![password_strength](https://user-images.githubusercontent.com/1425876/31486456-76bc786e-af2f-11e7-8be7-6ee2b453ccba.png)
