### ISSUE TITLE
Input Highlight Styles Consistency

### ISSUE THREAD

**Issue by nvasileiadis** [jadu/pulsar#695]
There have been detected at least three different highlight styles for input fields across Pulsar. All together can be seen in Form Helpers > Password

![input-highlights](https://user-images.githubusercontent.com/1425876/32940158-cc47bcf6-cb79-11e7-99b0-0be945696b67.png)
 
For that reason, there is a need to choose one for greater consistency among products.

**Comment by Stanton** [comment]
Seems to be a Pulsar issue when using Chrome + Password field + placeholder

Unable to replicate with plain unstyled password fields in codepen...

Still investigating.

**Comment by nvasileiadis** [comment]
The issue might be with the initialization
![hightlights](https://user-images.githubusercontent.com/1425876/34830221-1ed7ecf2-f6db-11e7-8185-111c2f0cd430.gif)

**Comment by nvasileiadis** [comment]
Noticed no highlight at all, at the latest Firefox (57.0.4). 

Strange caret in Safari: 
![strange-caret](https://user-images.githubusercontent.com/1425876/34981273-e7fbfe18-fa9e-11e7-9692-e886062ac48c.png)
