### ISSUE TITLE
Nav items don't break onto new lines when in 'small icon' mode

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#719]
<img width="341" alt="screen shot 2018-01-05 at 10 03 15" src="https://user-images.githubusercontent.com/18653/34604468-cddb7772-f1ff-11e7-96d8-d204e4c48774.png">

**Comment by Stanton** [comment]
<img width="341" alt="screen shot 2018-01-05 at 10 03 15" src="https://user-images.githubusercontent.com/18653/34604579-49757cf2-f200-11e7-9167-b8e2d047db93.png">

**Comment by nvasileiadis** [comment]
Even with the different markup provided I was not able to detect any difference in the classes after a diff. Not able to replicate the issue.
