### ISSUE TITLE
Add CSS (and other?) related build tasks to the CI runner

### ISSUE THREAD

**Issue by mikedevelops** [jadu/pulsar#735]
Certainly one for discussion – it seems a good idea to me to add CSS and potentially other tasks to the Travis CI tasks, this could help catch issues that manifest themselves as build failures. We'd also get the added benefit of running the tasks on a different environment than our local computers.

It will ofc make the CI build phase longer, which I think is a worthy trade off.

thoughts?

**Comment by nvasileiadis** [comment]
Yes, better check in Travis rather than creating new bugfix branches for newly merged work

**Comment by Stanton** [comment]
Added a year ago

1946de27bdb72f7aa6c7babe82d7b6f23309807a `Make Travis run grunt build task as part of build testing`
