### ISSUE TITLE
Various checkbox and radio display issues

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#762]
Inline checkboxes and radios are vertically misaligned:

![inline check boxes misaligned](https://user-images.githubusercontent.com/756393/36099012-002f69ec-0ff9-11e8-919c-79cf4bb107bd.png)
![inline radios are misaligned](https://user-images.githubusercontent.com/756393/36099015-025100aa-0ff9-11e8-9d0c-8ba7cc66f875.png)

Help block spacing issue:
![radio and checkbox help blocks spacing issue](https://user-images.githubusercontent.com/756393/36099022-0ef333aa-0ff9-11e8-9428-d664194e4ca9.png)

`form__group--full` breaks layout of radios and checkboxes:
![form__group--full breaks checkboxes](https://user-images.githubusercontent.com/756393/36099032-22848d42-0ff9-11e8-8027-93d5d2d159f6.png)
![form__group--full breaks radios](https://user-images.githubusercontent.com/756393/36099035-242914a6-0ff9-11e8-8a66-95d46b464912.png)

When a checkbox group is used there's an issue with target click area, meaning clicking a checkbox above another can uncheck/check the below checkbox:
![checkbox click area issue](https://user-images.githubusercontent.com/756393/36099184-99b853bc-0ff9-11e8-9344-108ba2582a95.gif)

Groups of checkboxes/radios (`form-choice`) are not vertically aligned with label:
![image](https://user-images.githubusercontent.com/756393/36100024-b0eb06bc-0ffc-11e8-971e-21aaa8579177.png)

**Comment by Stanton** [comment]
<img width="611" alt="screen shot 2018-02-12 at 13 34 14" src="https://user-images.githubusercontent.com/18653/36099132-797db15a-0ff9-11e8-9ae7-9078eb2404ac.png">

**Comment by jamesjacobs** [comment]
@Stanton what form group classes are being used there?

**Comment by Stanton** [comment]
@jamesjacobs 

```<div class="form__group form-choice form__group--full choice-block"><label class="control__label">Bookable days
            
        </label><div class="controls"><label class="control__label"><input name="bookableDays[]" value="1" checked="" type="checkbox" class="form__control checkbox"><span class="form-choice__label">Monday</span></label><label class="control__label"><input name="bookableDays[]" value="2" checked="" type="checkbox" class="form__control checkbox"><span class="form-choice__label">Tuesday</span></label><label class="control__label"><input name="bookableDays[]" value="3" checked="" type="checkbox" class="form__control checkbox"><span class="form-choice__label">Wednesday</span></label><label class="control__label"><input name="bookableDays[]" value="4" checked="" type="checkbox" class="form__control checkbox"><span class="form-choice__label">Thursday</span></label><label class="control__label"><input name="bookableDays[]" value="5" checked="" type="checkbox" class="form__control checkbox"><span class="form-choice__label">Friday</span></label><label class="control__label"><input name="bookableDays[]" value="6" type="checkbox" class="form__control checkbox"><span class="form-choice__label">Saturday</span></label><label class="control__label"><input name="bookableDays[]" value="7" type="checkbox" class="form__control checkbox"><span class="form-choice__label">Sunday</span></label></div></div>```

**Comment by jamesjacobs** [comment]
@Stanton What's on the `form__group`?

**Comment by Stanton** [comment]
Other than what's detailed up there? ☝️

**Comment by jamesjacobs** [comment]
Yeah, I don't see the `form__group` listed above

**Comment by Stanton** [comment]
<img width="799" alt="screen shot 2018-02-12 at 13 41 58" src="https://user-images.githubusercontent.com/18653/36099421-8468ecc8-0ffa-11e8-9155-edad8cd87457.png">

**Comment by jamesjacobs** [comment]
Strange, I only see from the closing `label`.

![screen shot 2018-02-12 at 13 42 28](https://user-images.githubusercontent.com/756393/36099455-a421a8c0-0ffa-11e8-84d4-c57b69923111.png)
