### ISSUE TITLE
Add a 'Getting started' guide page 

### ISSUE THREAD

**Issue by skmetaly** [jadu/pulsar#775]
A getting started page will help anyone who wants to start using pulsar into their own apps. Referencing things like
 - how to install Pulsar
 - how to install it's dependencies
 - what JS/CSS files needs to be defined
 - any project structure
 - possibly a small bootstrap HTML example

Docs example:
http://materializecss.com/getting-started.html

**Comment by Stanton** [comment]
https://jadu.github.io/pulsar/getting_started/
