### ISSUE TITLE
Tab order when triggering secondary navigation needs improvement

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#787]
**Current behavior:**
![secondary nav tab order](https://user-images.githubusercontent.com/756393/37783319-1908b920-2ded-11e8-949a-fbd753a2f21f.gif)

When you open the secondary navigation via keyboard, you have to tab through the rest of the primary nav items before being able to access the opened secondary nav links.

**Desired behavior:**
The next tab would take you to the secondary nav items. 

I've explored a few options, all of which would require breaking changes. The best options appear to be repeating the secondary navigation within each primary navigation `li` so natural tab order is preserved. This will require JS and CSS changes.

**Comment by Stanton** [comment]
Closed by #1257
