### ISSUE TITLE
Distribute Pulsar with NPM

### ISSUE THREAD

**Issue by mikedevelops** [jadu/pulsar#817]
Pulsar is predominantly a front-end framework, I think it is time we distributed it using a front-end package manager. There a few discussions to be had around the best way to do this.

Should Pulsar be sliced up into smaller chunks? e.g. A Pulsar Core package for all of the basic functionality and style. Then additional packages for extending the core functionality e.g Pulsar Nav bar Component. This will enable us to independently version and release Pulsar extensions, which should go some way to solving the problem of developing a new component / extension but then having to do a scary major pulsar release in the context / product it is being used.

It will also mean users of Pulsar can create more bespoke and lighter versions of Pulsar, they get to be declarative about which parts of Pulsar they get, rather than implicitly getting everything all the time, which I think contributes to the idea of updating Pulsar as a dependency scary.

Another benefit of this approach will allow us to remove any committed dependencies that we have in various `libs` folders within the repo, we all know now this is a bad idea and needs to be fixed.

One thing to think about is the PHP (twig) components that are in the Pulsar library. My suggestion for this is that they will continue to be distributed with composer (as they potentially may _have_ to be because of autoloading, need to research this though). Users that want to use Pulsar's twig helpers would need that dependency in composer something like "Pulsar Twig Helpers", then they would need to grab "Pulsar Core" from NPM to make use of the styles and javascript.

This is likely to be a hotly debated topic as it is fundamentally changing how Pulsar is used and will require work on any environment that uses Pulsar. This issue could serve as a place to post thoughts / concerns / excitement about this rather large chunk of work.

**Comment by Stanton** [comment]
I'm experimenting with the Twig side of things in XFP at the moment to see whether we actually need them to be brought in via Composer and be part of the autoloader, or if they can be brought in via NPM and still work with a product's Twig environment. Worst case is like you say Pulsar helpers may continue to be distributed by Composer.

**Comment by Stanton** [comment]
More information as I've been experimenting: The NPM versions of Twig helpers can be included, and used in the base template fine, however there is an issue with CMS+XFP where CMS sets the `@pulsar` twig variable is set by CMS to the composer path. 

If XFP creates a new `@pulsarXFP` then the npm versions are used, however anywhere in Pulsar where a helper includes another helper (like for helpers including the util helpers) then they use `@pulsar`, which then includes composer versions, causing a mix of both NPM and Composer helpers at potentially different versions.

Still investigating whether XFP can redefine the `@pulsar` variable without breaking CMS...

**Comment by Stanton** [comment]
Closing as speculative work, we may revisit this is a definite product need comes up.
