### ISSUE TITLE
Button dropdown links with `is-disabled` are not styled

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#831]
A link in a dropdown button list with the class `is-disabled` wont have any styling applied to it.

Also, upon clicking the link (or any link with a blank href) the dropdown will close as if an action is being actioned.

**Comment by Stanton** [comment]
> A link in a dropdown button list with the class is-disabled wont have any styling applied to it.

@jackbentley I'm unable to replicate this either by using the `is-disabled` class or the `disabled` option, could you please provide the HTML/Helper markup you're using?

### Test case
```
{{
    html.button_dropdown({
        'label': 'Drop Down',
        'items': [
            html.link({
                label: html.icon('print') ~ ' Print',
                'class': 'is-disabled'
            }),
            html.link({
                label: html.icon('lock') ~ ' Lock',
                disabled: true
            })
        ]
    })
}}
```

<img width="343" alt="screenshot 2018-06-07 at 09 35 31" src="https://user-images.githubusercontent.com/18653/41087969-23d90442-6a36-11e8-92ba-c71d7f86aef1.png">

**Comment by jackbentley** [comment]
Interesting, maybe it's the version we're using? I'll check and get back to you

**Comment by Stanton** [comment]
Shouldn’t be, this is very old functionality, but something smells screwy on your end...

**Comment by Stanton** [comment]
@jackbentley Were you able to figure this out?
