### ISSUE TITLE
Add option to prevent modals being closed when clicking outside

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#842]
Reported by Paul Johnson
> One thing I have noticed in the new form builder is that if you click outside any of the light boxes they close. I think, from speaking to Comets, that this is to do with the way in which they work in Pulsar. This can be quite frustrating as you can easily lose what you have been doing - especially if you have spent 10 minutes trying to create a mapping between and XForm and a CXM Case Type. Any thoughts?

**Comment by Stanton** [comment]
```$(document)
    .on('show.bs.modal',  '.modal', function () { $(document.body).addClass('modal-open') })
    .on('hidden.bs.modal', '.modal', function () {
      $(document.body).removeClass('modal-open');
    });```

**Comment by jamesjacobs** [comment]
This behaviour has been removed #1157
