### ISSUE TITLE
SelectWoo Integration styles

### ISSUE THREAD

**Issue by mikedevelops** [jadu/pulsar#844]
The Pulsar `_component.select2.scss` overrides need tweaking for the new SelectWoo plugin. From initial testing it looks as though anything that hangs off of `[aria-selected]` will need changing to `[data-selected]`, I'll keep a list of rules here that need to go in CXMs scratch file so they can be merged into Pulsar.

```
.select2-container--default .select2-results__option[data-selected="true"] {
    background-color: #ddd;
}
```

```
.select2-container--default .select2-results__option--highlighted[data-selected="true"] {
    background-color: #5897fb;
    color: white;
}
```

**Comment by jamesjacobs** [comment]
Resolved by #992
