### ISSUE TITLE
form__control width modifiers are being overridden

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#848]
`form__control-col--X` and the legacy `form__control--X` are being overridden by more specific styles.

To clarify, this:
```
.control__label + .controls > .form__control.form__control-col--1
```

is being overridden by:
```
.control__label + .controls > .form__control:not(.checkbox):not(.radio)
```

**Comment by Stanton** [comment]
Fixed here: https://github.com/jadu/pulsar/commit/e7a5bca55e3ca45857a8f657429a52cb6a9c0473#diff-b0ffa62f7b70dea4f47f07c4d8ead0d3

Released in `[7.0.4](url
https://github.com/jadu/pulsar/releases/tag/7.0.4)`
