### ISSUE TITLE
Table detail pattern adds multiple backdrops when using pagination

### ISSUE THREAD

**Issue by mikedevelops** [jadu/pulsar#874]
Issue reported here: https://jadu.slack.com/archives/C0BS5U1N3/p1535624320000100

When navigating the pages of a data table, a new backdrop is added for each page, this means that when opening the details pane, multiple instances of the backdrop are visible.

![screen shot 2018-08-30 at 11 25 02](https://user-images.githubusercontent.com/9677023/44846423-344ec380-ac48-11e8-8851-c7ee276fe541.png)

**Comment by Stanton** [comment]
Unable to replicate this issue in Lexicon, and there have been multiple changes since this ticket has been created. Fairly sure it's no longer an issue.
