### ISSUE TITLE
Combination of Masterswitch and Modal

### ISSUE THREAD

**Issue by nvasileiadis** [jadu/pulsar#876]
In CMS and specifically at Email Settings there is a case with the masterswitch triggering a modal to ask the users if they really need to disable those options. The ideal case would be the toggle to be clickable only. At the moment, the component in its entirety is.

![masterswitch modal](https://user-images.githubusercontent.com/1425876/45292359-e0b46380-b4ec-11e8-921c-ca91d9891cf1.gif)

**Comment by Stanton** [comment]
Wouldn't recommend having a toggle switch trigger a modal, the masterswitch pattern's method of visually disabling fields should be enough, if an additional step is required perhaps the masterswitch pattern should be replaced with something else.
