### ISSUE TITLE
Date picker placeholder doesn't reflect format option

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#886]
**Observed**

Supplying `US` or `reverse` option displays UK date placeholder.

![screenshot 2018-09-24 at 13 47 14](https://user-images.githubusercontent.com/18653/45952900-5b5aa400-c000-11e8-8717-d1f18aa5b94a.png)

**Expected**

Placeholder should reflect the expected date format.

**Comment by nvasileiadis** [comment]
Where can I find this interface @Stanton ? Doesn't seem to be Lexicon or docs. Is it the new docs?

**Comment by Stanton** [comment]
Can be replicated with the same twig, create a date helper without specifying a placeholder.
