### ISSUE TITLE
Twig helpers for select don't allow pre selected values with multiple

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#905]
Can't use `selected` option with `multiple` option `true` in the twig helpers for `select` and `select2`.

Additionally, this stops being able to add a `selected` option to the `choice` twig helper.

## Test case

```twig
{{
    form.select({
        'label': 'Deselect some',
        'options': [
            { 'label': 'a', 'value': 'a' },
            { 'label': 'b', 'value': 'b' },
        ],
        'selected': ['a', 'b'],
    })
}}
```

## Expected

A select is rendered with both `a` and `b` options pre-selected.

## Actual

Select is loaded with no selected options.

**Comment by Stanton** [comment]
@jackbentley Is this required for current work? If so could you please let me know timescales involved so I can prioritise it? Cheers :)

**Comment by Stanton** [comment]
@jackbentley Is this required for current work? If so could you please let me know timescales involved so I can prioritise it? Cheers :)
