### ISSUE TITLE
After jumping to a #fragment you can't scroll back to the top of the window.

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#912]
**Describe the bug**
After clicking a link that takes you to a fragment you can't scroll back to the very top of the UI.

**To Reproduce**
1. Add a link to a page #fragment
2. Click on the link and jump to the fragment
3. Try to scroll back to the top of the UI
4. You are unable to see the very top of the UI.

**Expected behavior**
You should be able to scroll back to the very top of a UI.

**Screenshots**
Here's a SS from the lexicon of scrolling to the top of the UI after clicking an anchor link:

![image](https://user-images.githubusercontent.com/756393/47907084-767fc580-de82-11e8-89f9-984683f3962e.png)

The problem seem to be worse in product:

![screen_shot_2018-10-24_at_11 21 23](https://user-images.githubusercontent.com/756393/47907131-8b5c5900-de82-11e8-9125-82e0d622ed02.png)

And much worse at smaller VP widths:
![image](https://user-images.githubusercontent.com/756393/47907361-032a8380-de83-11e8-910c-4b4510ea0d4d.png)

**Desktop:**
So far I've only tested in chrome. See above screenshots.

**Smartphone:**
Issue is worse at smaller viewports width. Not tested on device, just in chrome responsive mode.

**Comment by Stanton** [comment]
Closed by #946
