### ISSUE TITLE
Buttons have very thin text in chrome

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#920]
Button text is hard to read in chrome. I don't remember this always being the case, so may be down to a recent change. Interestingly the issue does not seem to exist in the lexicon in chrome. The button styles in product vs lexicon match exactly too.

Needs testing in all browsers. I've noticed the issue is not present in Safari.

**Screenshots**
Example button from CXM (chrome):
![screenshot 2018-11-07 at 16 33 08](https://user-images.githubusercontent.com/756393/48145851-a7f5f800-e2ab-11e8-93f6-73f6ea0f5d55.png)

The same button displayed in the lexicon (chrome):
![screenshot 2018-11-07 at 16 33 14](https://user-images.githubusercontent.com/756393/48145868-af1d0600-e2ab-11e8-989c-8c397f4e6777.png)

**Comment by jackbentley** [comment]
Might be something to do with WebKit font smoothing on a parent element?

**Comment by jamesjacobs** [comment]
Issue only effects Chrome (and some non browser apps). Seems to be a bug specific to Mojave on non retina screens. Found various related reports:

https://github.com/Microsoft/vscode/issues/51132
https://www.reddit.com/r/MacOS/comments/8ol061/anyone_else_feel_the_text_is_slightly_less_bold/
https://stackoverflow.com/questions/52485803/mac-os-x-mojave-font-thinner-on-chrome-how-to-fix
https://www.reddit.com/r/MacOS/comments/9n9jdv/situation_with_font_rendering_on_macos_mojave_and/
https://bugs.chromium.org/p/chromium/issues/detail?id=858861#c30

Closing issue as it seems it's specific to Mojave on non retina screens and not related to Pulsar.
