### ISSUE TITLE
Add ability for prepended calendar icon to open pikaday in date helper

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#924]
**Is your feature request related to a problem? Please describe.**
When using a prepended calendar icon to illustrate a date field, it's not possible to open the date dropdown.

![date-cal](https://user-images.githubusercontent.com/18653/48631827-56d6ba00-e9b7-11e8-8f5b-62bdb6b6553b.gif)
----
**Describe the solution you'd like**
Perhaps easiest way would be for the icon to focus the date field when clicked, this may be useful in other helpers.

**Additional context**
Raised during usability testing for CMS event recurrence feature.

**Comment by Stanton** [comment]
@asmblah Does Dynamic provide anything that would allow us to easily declare this behaviour (toggle focus of a field on click) via data-attributes?

**Comment by jamesjacobs** [comment]
From an accessibility point of view I'd consider:
1. Make the appended icon an appended (or maybe prepended 🤔 ) button
2. Use `aria-haspopup` / `aria-expanded` / `aria-controls` (the first 2 may be enough).

**Comment by asmblah** [comment]
@Stanton yes - there's an (extremely simple) example at the bottom of this page: https://asmblah.github.io/dynamic-extras/

You can also add custom behaviours if needed.

**Comment by Stanton** [comment]
Closing as we're retiring Pikaday
