### ISSUE TITLE
Toggle switch can be toggled in unexpected places

### ISSUE THREAD

**Issue by mikedevelops** [jadu/pulsar#927]
**Describe the bug**
Toggle buttons can be toggled in odd places. Looks as though a combination of toggles being inside labels and labels being full width means I can click wayyy off to the right and toggle a toggle by mistake.

**To Reproduce**
This can be reproduced within CXM in Settings -> System -> Integrations HUB.
I suspect this can be reproduced in the Lexicon also.

**Expected behavior**
I expect to click the label and toggle the toggle, however it's unexpected that I can click to the right of the toggle (which is actually label) and toggle the toggle.

**Screenshots**
![toggle](https://user-images.githubusercontent.com/9677023/49143813-c15ef280-f2f3-11e8-9d4b-bcd032a936cf.gif)

**Desktop (please complete the following information):**
 - OS: OSX High Sierra
 - Browser: Chrome
 - Version: 70

**Comment by Stanton** [comment]
Blocks are full width to support help text, this won't be a simple fix...

![screenshot 2019-01-04 at 09 59 55](https://user-images.githubusercontent.com/18653/50682665-84c79a80-1007-11e9-935c-2440db5a36c7.png)
