### ISSUE TITLE
Improve radio buttons in action templates

### ISSUE THREAD

**Issue by markbjadu** [jadu/pulsar#932]
Clicking on a radio button the orange helper appears but looks wrong.

1. Go to 'Rules' page
2. Create a new  'Export as file' rule
3. Fill out the tabs until 'Fields to Export'
4. On the 'Fields to include' select one.

**Expected behavior**
Better styling of the orange square on radio button

![screenshot 2019-01-04 at 10 52 40](https://user-images.githubusercontent.com/6906173/50697840-4a77f080-103b-11e9-8e9a-fd7446d4cd08.png)

**Desktop (please complete the following information):**
 - OS: mac OS 10.14.2
 - Browser Chrome
 - Version 71.0.3578.98

**Additional context**
Could happen in other browsers.

**Comment by Stanton** [comment]
Fixed by #935
