### ISSUE TITLE
Improve colour contrast help text in certain areas.

### ISSUE THREAD

**Issue by markbjadu** [jadu/pulsar#934]
Improve colour contrast help text in certain areas.

1. Create a form and page.
2. Add event booking element
3. On the settings of the element see the help text for 'Concurrency Weighting'

The colour contrast could be improved or the size of the text.

OS: mac OS 10.14.2
Browser Chrome
Version 71.0.3578.98

Could happen in other browsers

![helptext](https://user-images.githubusercontent.com/6906173/51264443-69b53d00-19ae-11e9-8df9-b73b286721f7.png)

**Comment by Stanton** [comment]
@jamesjacobs did your recent change address this at all?

**Comment by Stanton** [comment]
Released circa 9.1.0
