### ISSUE TITLE
Input borders do not meet WCAG 2.1 (1.4.11) contrast success criteria

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#942]
**Describe the bug**
Currently all inputs have a `1px solid #bebebe` border which has a colour contrast of 1.86:1 which is below the required contrast of 3.1 for user interface components.

See https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html

This effects all inputs apart from the file input. Toggle switches, range, checkboxes and radios are also effected though may use alternatives to border.

**Comment by Stanton** [comment]
Fixed in #943

**Comment by Stanton** [comment]
Fixed in #943
