### ISSUE TITLE
[RFC] Create flash.summary component to display form validation errors

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#956]
Following some discussion and research it has been decided that form summary errors should be physically located within (or in the same position as) flash messages.

The proposal is to create a new `flash.summary` component to be used when form validation fails.

The `flash.message` component will still be used for singular error messages, not relating to form validation errors.

# Visuals

![Screenshot 2019-03-20 at 13 25 55](https://user-images.githubusercontent.com/18653/54687647-02ce1480-4b14-11e9-97c0-d2fe4ad5c270.png)

# Helper

A `flash.summary` helper will be created which will accept an array of errors to display. The format of this array is up for debate although at it's simplest it just needs to include a string message and an ID target for the link.

Example:

```
{{
    flash.summary({
        items: [
            {  
                'label': 'Enter a first name',
                'href': '#firstName'
            },
            {  
                'label': 'Enter a postcode, like LE19 1RJ',
                'href': '#postCode'
            },
            {  
                'label': 'Confirm you accept the terms and conditions',
                'href': '#confirm'
            }
        ]
    })
}}
```

This could either only allow danger styling, or it could support all state variations through a BEM class like `summary--success` `summary--danger` etc, however this would require us to also allow a title value rather than the recommended error title of 'There is a problem' which can be hardcoded for consistency.

**Comment by jackbentley** [comment]
How will this integrate with Symfony's flash messages and Symfony Forms?

**Comment by Stanton** [comment]
@jackbentley Pulsar doesn't yet support these natively

**Comment by Stanton** [comment]
![Screenshot 2019-03-21 at 10 42 38](https://user-images.githubusercontent.com/18653/54747173-11750400-4bc6-11e9-93cb-d2bd4b19842f.png)

**Comment by Stanton** [comment]
https://pulsar.docs.jadu.net/forms/error-summary
