### ISSUE TITLE
Drop down arrow in XForms control centre is in wrong place

### ISSUE THREAD

**Issue by markbjadu** [jadu/pulsar#957]
Drop down arrow in XForms control centre is in wrong place.

1. Create a new form
2. Go to 'Advanced' tab
3. Create a logic.

Expected: The arrow for drop down should be on the end of it.

 - Mac OS 10.14.3
 - Chrome
 - 73.0.3683.86

![Screenshot 2019-03-21 at 10 40 06](https://user-images.githubusercontent.com/6906173/54747394-b1cb2880-4bc6-11e9-8866-8211dad013c6.png)

![Screenshot 2019-03-21 at 10 32 56](https://user-images.githubusercontent.com/6906173/54747396-b1cb2880-4bc6-11e9-863b-63e37f027e37.png)

**Comment by Stanton** [comment]
@markbjadu Field uses the `form__group--full` modifier, the width is correct documented behaviour and will not be addressed as part of this ticket.

We will, however, improve the position of the dropdown arrow.
