### ISSUE TITLE
Appended content breaks container in IE11

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#965]
**Describe the bug**
Using a small width modifier (such as `form__group--small`) can cause the appended content to break outside of the appended container.

**To Reproduce**
```
{{
    form.text({
        'id': 'text-29',
        'label': 'Appended',
        'append': 'Minutes',
        'class': 'form__group--mini'
    })
}}
```

**Expected behavior**
Appended content should not break the container and behave similarly to prepended content.

**Screenshots**

**IE11**
![Screenshot 2019-04-25 at 09 41 29](https://user-images.githubusercontent.com/18653/56722211-8051f980-673e-11e9-9292-fa7a58e91a49.png)

**Safari**
![Screenshot 2019-04-25 at 09 42 18](https://user-images.githubusercontent.com/18653/56722219-85af4400-673e-11e9-84fe-432901e7d1c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser IE
 - Version 11

**Additional context**
Reported by @markbjadu and affecting production UIs.

**Comment by jamesjacobs** [comment]
Fixed by #966
