### ISSUE TITLE
Create pattern and helper for text range form components

### ISSUE THREAD

**Issue by langy** [jadu/pulsar#98]
Sometimes a need will arise to place two components next to each other, for example "From: input for something" "To: input for something".

With our current helpers this isn't very easy to achieve, so raw mark-up might be used instead. This is never ideal, as it carries the potential to become out of date at some point and subsequently introduce more issues.

One option could be a `form.range()` helper, which could be set to text, date, time, slider etc.

**Comment by langy** [comment]
Example: ![screen shot 2016-03-09 at 12 15 19](https://cloud.githubusercontent.com/assets/713141/13634940/a819b872-e5f0-11e5-840e-6b9802cc7cb9.png)

**Comment by Stanton** [comment]
Date range plugin: http://eternicode.github.io/bootstrap-datepicker/?markup=range&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=2&todayBtn=linked&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

**Comment by Stanton** [comment]
Closing until we have a specific use case.
